export type { Direction, Mobile, DogIntent } from "./types.js";
export { directionFromVelocity } from "./direction.js";
export { config } from "./config.js";
export { seek, flee, arrive } from "./steering/primitives.js";
export type { Status, SteerContext, BehaviorNode, Predicate } from "./steering/types.js";
export { blend } from "./steering/Behavior.js";
export type { WeightedChild } from "./steering/Behavior.js";
export { separation, cohesion, follow, graze, obstacleAvoid } from "./ai/behaviors.js";
export { buildSheepTree } from "./ai/trees.js";
export type { Sheep, SheepTraits } from "./entities/Sheep.js";
export { createSheep, defaultSheepTraits } from "./entities/Sheep.js";
export type { GrassField, GrassFieldOptions } from "./grass/GrassField.js";
export { createGrassField, densityAt, setDensityAt, depleteAt, regrow, gradientAt } from "./grass/GrassField.js";
export { grassSystem } from "./systems/GrassSystem.js";
export { driveSystem } from "./systems/DriveSystem.js";
export { neighborhoodSystem } from "./systems/NeighborhoodSystem.js";
export { steeringSystem } from "./systems/SteeringSystem.js";
export { movementSystem, integrate } from "./systems/MovementSystem.js";
export type { World, Rect } from "./world/World.js";
export { createWorld } from "./world/World.js";
export { Game } from "./world/Game.js";
export type { Obstacle, ObstacleKind } from "./entities/Obstacle.js";
export { createObstacle } from "./entities/Obstacle.js";
export { collisionSystem } from "./systems/CollisionSystem.js";
export type { SteerEnv } from "./systems/SteeringSystem.js";
export type { PenShape, PenGenOptions } from "./world/penGen.js";
export { generatePen } from "./world/penGen.js";
export type { Pen, Segment } from "./world/Pen.js";
export { buildPen, penContains } from "./world/Pen.js";
export { penSystem } from "./systems/PenSystem.js";
